name: m4d_flux
description: Material Design 4 Dart - Flux-Datastore
version: 0.1.0
author: Mike Mitterer <office@mikemitterer.at>
homepage: https://github.com/MikeMitterer/m4d_flux

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  validate: ^1.0.0

  logging: '>=0.11.3 <1.0.0'
  console_log_handler: ^1.0.0

dev_dependencies:
  test: any

  build_runner: any
  build_test: any
  build_web_compilers: any
